### PR TITLE
Changes to Evans page and addition of K. Bishop page.

### PR DESCRIPTION
**Pull request by mizejewski**
NOTE: Things look broken in my Dreamweaver preview, but it might just
be the way this site is built? Hoping the extra code I’m seeing is not
visible on live pages (e.g. {% include search_include.html %}.) Also,
placeholder images will be swapped once real one is approved.

### CODE REVIEW

**Comment by Trott** [comment]
The extra code is probably because you would need to run jekyll to get a full and proper preview!

**Comment by Trott** [comment]
Should I go ahead and push it live with the placeholder images? Or hold off until the real ones come through?

**Comment by mizejewski** [comment]
I'll verify with Polina, but she got the requests from the Chancellor and seemed to want the changes ASAP even if the image permission hasn't yet come through. I'll let you know what she says...

Thanks,

Michele

Michele Mizejewski

On Mar 25, 2014, at 9:31 PM, "Rich Trott" <notifications@github.com<mailto:notifications@github.com>> wrote:

Should I go ahead and push it live with the placeholder images? Or hold off until the real ones come through?

**Comment by mizejewski** [comment]
Is that something that goes in metadata, or should it be readable? The others don’t appear to have a credit.

For example: http://history.library.ucsf.edu/bishop.html

If you want it on the page, do you prefer it below the references?

Thanks,

Michele Mizejewski
Web Initiatives Librarian
University of California, San Francisco

**Comment by mizejewski** [comment]
Just heard from Polina and I’m updating images now. I’mm let you know when to push live.

Thanks,

Michele Mizejewski
Web Initiatives Librarian
University of California, San Francisco

**Comment by mizejewski** [comment]
Yes, Jekyll did give a more true preview. I wasn’t sure if it worked for html pages as well as markdown.

On that topic, I use Dreamweaver because it’s what I have. Short of a plain text editor, is there an alternate you’d recommend? Coda2 seems good and integrates with Git, but I don’t have much experience with it.

Thanks,

Michele Mizejewski
Web Initiatives Librarian
University of California, San Francisco

**Comment by Trott** [comment]
I don't have an editor recommendation for HTML previews and stuff. I'm afraid you'll have to ask someone else and/or do some research on it. It's not something I have expertise in. If you do find something you like, I'd love to know what it is (so I can play with it and/or recommend it to others).

**Comment by mizejewski** [comment]
OK, I’ll ask/look around and let you know.

Thanks,

Michele Mizejewski
Web Initiatives Librarian
University of California, San Francisco

**Comment by mizejewski** [comment]
Just committed more changes and made another pull request. Ready to go live now.

Thanks,

Michele Mizejewski
Web Initiatives Librarian
University of California, San Francisco

**Pull request merged**
